[package]
name = "project-euler"
version = "1.0.0"
edition = "2021"

[dev-dependencies]
divan = "0.1.13"

[[bench]]
name = "benches"
harness = false

[profile.release]
incremental = true
strip = "debuginfo"
