name: lint
on:
  push:
    paths:
      - '.github/workflows/lint.yml'
      - '**.rs'
  workflow_dispatch:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo clippy
