name: sanity
on: [push, workflow_dispatch]

jobs:
  sanity:
    name: sanity on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: cargo -vv build --release
      - run: cargo -vv run --release
