name: sanity
on: [push, workflow_dispatch]

jobs:
  sanity32:
    name: sanity on 32-bit alpine:3.19
    runs-on: ubuntu-22.04
    steps:
      - uses: docker/setup-buildx-action@v3
      - uses: docker/build-push-action@v5
        with:
          push: false
          tags: sanity32
      - uses: addnab/docker-run-action@v3
        with:
          image: sanity32
          run: cargo -vv run release
  sanity64:
    name: sanity on 64-bit ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: cargo -vv run --release
