name: style
on:
  push:
    paths:
      - 'rustfmt.toml'
      - '**.rs'
  workflow_dispatch:

jobs:
  style:
    name: style
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo fmt -v --check
