name: tests
on: [push, workflow_dispatch]

jobs:
  tests:
    name: tests on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, ubuntu-22.04, windows-2022]
    steps:
      - uses: actions/checkout@v4
      - run: cargo build --release
      - run: cargo run --release
