name: tests
on:
  push:
    paths:
      - src/utils.rs
  workflow_dispatch:

jobs:
  tests:
    name: tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --release
