name: tests
on:
  push:
    paths:
      - src/utils.rs

jobs:
  tests-i686:
    name: tests-i686
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker build .
  tests-amd64:
    name: tests-amd64
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - run: cargo test --release
